export const ALL_PRODUCTS = "ALL_PRODUCTS";
export const PRODUCT_BY_CATEGORY = "PRODUCT_BY_CATEGORY";
export const USER_REGISTER = "USER_REGISTER";
export const GET_STORES = "GET_STORES";
// export const USER_LOGIN = "USER_LOGIN";
// export const REGISTER_BUYER = "REGISTER_BUYER";
